theme = "awesome-identity"
baseURL = "https://yuhsuan105.github.io/"
title = "YuHsuan Chen"


## Profile Configurations
[params.profile]
  portrait = "/images/bachelor_graduation_cut1.jpg"
  firstname = ""
  lastname = "YuHsuan Chen"
  title = ""
  bio = """剛畢業並服完兵役的新鮮人

  對資訊科學領域充滿興趣，並時常會學習一些相關知識與技術
  """

## Contacts Configurations
[params.contacts]
  email = "yuhsuanchen105@gmail.com"
  github = "yuhsuan105"
  linkedin = "yuhsuan105"

## Actions
[params.actions]
  cv = {url="/cv/yuhsuanchen_cv.pdf", name="Review My CV"}

## Footer Configurations
[params.footer]
  copyright = "© 2021 YuHsuan Chen."
  poweredBy = true
